server:
  port: 8889

spring:
  datasource:
    url: jdbc:mysql://47.116.14.251:3306/balls?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root1234
  redis:
    database: 0
    host: 47.116.14.251
    port: 6388
    password: ljx888hh
    timeout: 1000
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

mybatis:
  type-aliases-package: com.balls.pojo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

